const keywords = {
  reject: [
    "wordpress",
    "wordpress plugin",
    "webflow",
    "bubble",
    "nft",
    "crypto",
    "blockchain",
    "ai prompt",
    "wix",
    "squarespace",
    "shopify theme",
    "flutter",
    "swift",
    "kotlin",
    "ios only",
    "android only",
    "mobile only",
    "unity",
    "unreal",
    "game dev",
    "game development",
    "natural language processing",
    "nlp",
    "data science",
    "data scientist",
    "ml engineer",
    "ai engineer",
    "chatgpt",
    "langchain",
    "llm",
    ".net framework",
    "asp.net",
    "asp.net mvc",
    ".net core",
    "c#",
    "django",
    "laravel",
    "agora sdk",
    "agora",
    "live streaming technology",
    "francais",
    "french",
    "data analysis",
    "financial modeling",
    "google sheets",
    "excel",
    "amazon fba",
    "amazon ppc",
    "amazon webstore",
    "hazop",
    "ruby on rails",
    "angular",
    "vue.js",
    "svelte",
    "php",
    "power bi",
    "powerbi",
    "jasper",
    "jaspersoft",
    "tibco",
    "ssrs",
    "report builder",
    "oracle rdb",
    "powerpoint",
    "presentation design",
    "sales deck",
    "logo design",
    "packaging design",
    "graphic design",
    "dielines",
    // Non-Node backends (user only does Node/Express/Nest) — see [[user-profile]]
    "golang",
    "go developer",
    "spring boot",
    "spring framework",
    // No-code / low-code platforms (not dev work)
    "zapier",
    "airtable",
    "softr",
    "gohighlevel",
    "go high level",
    "highlevel",
    "housecall pro",
    "commonsku",
    "magento",
    // Marketing / analytics / ads (not dev work)
    "google tag manager",
    "tracking specialist",
    "meta ads",
    "facebook ads",
    "google ads",
    "seo expert",
    "seo specialist",
    "seo optimization",
    "market research",
    // Testing-/teaching-/assistant-only roles
    "performance testing",
    "tutoring",
    "tutor needed",
    "personal assistant",
    // Hardware / IoT / AR (not web dev)
    "augmented reality",
    "webar",
    "bluetooth low energy",
    "apple find my",
    // Browser extensions (user not experienced)
    "chrome extension",
    "browser extension",
    // IoT / embedded / hardware (not web dev)
    "firmware",
    "embedded systems",
    "embedded engineer",
    "iot system",
    "iot device",
    "internet of things",
    "satellite",
    "rf engineer",
    // Shopify — TEMPORARILY disabled per user 2026-06-29 ("get it back soon").
    // REMOVE these two lines to re-enable Shopify leads.
    "shopify",
    "shopify plus",
    // Social-media content / marketing (not app dev)
    "reels",
    "instagram",
    "cro consultant",
    "conversion rate optimization",
    // Content creation / video editing
    "content creation",
    "capcut",
    "youtube content",
  ],

  rejectUnlessWebDev: [
    "python",
    "artificial intelligence",
    "generative ai",
    "machine learning",
    "prompt engineering",
  ],

  rejectSkillsStrict: [
    "agora sdk",
    "live streaming technology",
    "francais",
    "data analysis",
    "financial modeling",
    "amazon fba",
    "amazon ppc",
    "amazon webstore",
    "hazop",
    "microsoft power bi",
    "power bi",
    "jaspersoft studio",
    "tibco jasper",
    "microsoft sql server reporting services",
    "oracle rdb",
    "microsoft powerpoint",
    "presentation design",
    "business presentation",
    "graphic design",
    "packaging design",
    "logo design",
  ],

  rejectTitles: [
    "operations manager",
    "account manager",
    "amazon manager",
    "ppc specialist",
    "hazop specialist",
    "social media manager",
    "content creator",
    "seo specialist",
    "data analyst",
    "financial analyst",
    "bookkeeper",
    "virtual assistant",
    "video editor",
    "copywriter",
    "translator",
    "powerpoint",
    "sales deck",
    "logo design",
    "packaging",
    "power bi",
    "powerbi",
    "jasper",
    "tibco",
    "ssrs",
    "report developer",
    "report builder",
    "us based",
    "u.s. based",
    "us-based",
    "us only",
    "u.s. only",
    "usa only",
    "united states only",
    "uk based",
    "uk-based",
    "uk only",
    "europe based",
    "european based",
    "eu based",
    "eu only",
    "european only",
    "canada based",
    "canada only",
    "australia based",
    "australia only",
    // Sales / commission roles (not dev work)
    "sales partner",
    "sales representative",
    "sales rep",
    "sales executive",
    "high-commission",
    "high commission",
    "commission-only",
    "commission only",
    // Ops / support roles (not dev work)
    "ops support",
    "ops specialist",
    "operations specialist",
    "support specialist",
    "customer support",
    "personal assistant",
    "market research",
    "visual artist",
    "seo expert",
    "website design",
    "web design",
  ],

  // Testing-focused titles. REJECTED only when the title has no dev signal —
  // a "QA Engineer" / "Test Engineer" / "Manual Testing" post is testing-only,
  // but a "Full Stack Developer" role that also mentions testing is fine.
  // (Kept separate from rejectTitlesUnlessDev because its dev-check must NOT
  // treat the bare word "engineer" as dev — "QA Engineer" contains it.)
  rejectTitlesTestingOnly: [
    "qa engineer",
    "qa tester",
    "qa analyst",
    "quality assurance",
    "test engineer",
    "manual testing",
    "software tester",
    "automation tester",
    "sdet",
  ],

  rejectTitlesUnlessDev: [
    "ui/ux designer",
    "ux designer",
    "ui designer",
    "ui/ux",
    "graphic designer",
    "product designer",
    "product design",
    "design specialist",
    "senior designer",
    "lead designer",
    "designer",
  ],

  redFlagPhrases: [
    "work incrementally to build trust",
    "without an hourly wage",
    "build trust first",
    "start with small task",
    "test task",
    "unpaid trial",
    "free sample",
    "prove yourself",
    "trial period with no pay",
    "equity only",
    "revenue share only",
  ],

  // Urgency signals - client is ready to hire NOW (closeable)
  urgencyKeywords: [
    "asap",
    "immediately",
    "urgent",
    "start today",
    "start immediately",
    "need someone now",
    "right away",
    "ready to hire",
    "start this week",
  ],

  highPriority: {
    react: { keywords: ["react", "reactjs", "react.js"], points: 3 },
    nextjs: { keywords: ["next.js", "nextjs", "next js"], points: 3 },
    node: { keywords: ["node.js", "nodejs", "node js"], points: 3 },
    express: { keywords: ["express", "expressjs", "express.js"], points: 3 },
    fullstack: {
      keywords: ["full stack", "fullstack", "full-stack"],
      points: 3,
    },
  },

  mediumPriority: {
    postgresql: { keywords: ["postgresql", "postgres", "psql"], points: 2 },
    dashboard: {
      keywords: ["dashboard", "admin panel", "admin dashboard"],
      points: 2,
    },
    saas: { keywords: ["saas", "software as a service"], points: 2 },
    typescript: { keywords: ["typescript", "ts"], points: 2 },
    webapp: {
      keywords: ["web app", "web application", "web platform"],
      points: 2,
    },
    mvp: { keywords: ["mvp", "minimum viable product", "prototype"], points: 2 },
    internaltool: {
      keywords: ["internal tool", "internal dashboard", "back office"],
      points: 2,
    },
  },

  lowPriority: {
    tailwind: { keywords: ["tailwind", "tailwindcss"], points: 1 },
    api: {
      keywords: ["rest api", "api development", "api integration"],
      points: 1,
    },
    supabase: { keywords: ["supabase"], points: 1 },
    vercel: { keywords: ["vercel"], points: 1 },
    netlify: { keywords: ["netlify"], points: 1 },
    railway: { keywords: ["railway"], points: 1 },
    aws: { keywords: ["aws", "amazon web services", "s3", "ec2"], points: 1 },
    auth: { keywords: ["authentication", "auth", "oauth", "jwt"], points: 1 },
    stripe: { keywords: ["stripe", "payment integration", "payments"], points: 1 },
    crud: { keywords: ["crud", "data table", "data grid"], points: 1 },
  },

  // Specialty boosts — reward the things Peter is uniquely strong at (verified
  // across halla/limitless/incarton/restaurant/xtrack). One match per category.
  // Scored separately from the stack keywords so the daily report shows it.
  specialtyKeywords: {
    payments: {
      keywords: [
        "stripe",
        "payment integration",
        "payment gateway",
        "subscription billing",
        "recurring billing",
        "billing system",
        "checkout flow",
        "paypal",
        "marketplace payout",
        "metered billing",
      ],
      points: 3,
    },
    multiTenant: {
      keywords: ["multi-tenant", "multitenant", "multi tenant", "b2b saas", "saas platform"],
      points: 3,
    },
    booking: {
      keywords: [
        "booking",
        "reservation",
        "reservations",
        "scheduling",
        "appointment",
        "availability calendar",
      ],
      points: 2,
    },
    realtime: {
      keywords: ["real-time", "realtime", "websocket", "socket.io", "live updates"],
      points: 1,
    },
    verticals: {
      keywords: [
        "insurance",
        "logistics",
        "freight",
        "warehouse",
        "inventory management",
        "restaurant",
        "hospitality",
        "event management",
        "ticketing",
        "erp",
      ],
      points: 1,
    },
  },
};

module.exports = keywords;
