const keywords = {
  reject: [
    "wordpress",
    "webflow",
    "bubble",
    "nft",
    "crypto",
    "blockchain",
    "ai prompt",
    "wix",
    "squarespace",
    "shopify theme",
    "flutter",
    "swift",
    "kotlin",
    "ios only",
    "android only",
    "mobile only",
    "unity",
    "unreal",
    "game dev",
    "game development",
    "natural language processing",
    "nlp",
    "data science",
    "data scientist",
    "ml engineer",
    "ai engineer",
    "chatgpt",
    "langchain",
    "llm",
    ".net framework",
    "asp.net",
    "asp.net mvc",
    ".net core",
    "c#",
    "django",
    "laravel",
    "agora sdk",
    "agora",
    "live streaming technology",
    "francais",
    "french",
    "data analysis",
    "financial modeling",
    "google sheets",
    "excel",
    "amazon fba",
    "amazon ppc",
    "amazon webstore",
    "hazop",
    "ruby on rails",
    "angular",
    "vue.js",
    "svelte",
    "php",
  ],

  rejectUnlessWebDev: [
    "python",
    "artificial intelligence",
    "generative ai",
    "machine learning",
    "prompt engineering",
  ],

  rejectSkillsStrict: [
    "agora sdk",
    "live streaming technology",
    "francais",
    "data analysis",
    "financial modeling",
    "amazon fba",
    "amazon ppc",
    "amazon webstore",
    "hazop",
  ],

  rejectTitles: [
    "operations manager",
    "account manager",
    "amazon manager",
    "ppc specialist",
    "hazop specialist",
    "social media manager",
    "content creator",
    "seo specialist",
    "data analyst",
    "financial analyst",
    "bookkeeper",
    "virtual assistant",
    "video editor",
    "copywriter",
    "translator",
  ],

  rejectTitlesUnlessDev: [
    "ui/ux designer",
    "ux designer",
    "ui designer",
    "graphic designer",
    "product designer",
  ],

  redFlagPhrases: [
    "work incrementally to build trust",
    "without an hourly wage",
    "build trust first",
    "start with small task",
    "test task",
    "unpaid trial",
    "free sample",
    "prove yourself",
    "trial period with no pay",
    "equity only",
    "revenue share only",
  ],

  // Urgency signals - client is ready to hire NOW (closeable)
  urgencyKeywords: [
    "asap",
    "immediately",
    "urgent",
    "start today",
    "start immediately",
    "need someone now",
    "right away",
    "ready to hire",
    "start this week",
  ],

  highPriority: {
    react: { keywords: ["react", "reactjs", "react.js"], points: 3 },
    nextjs: { keywords: ["next.js", "nextjs", "next js"], points: 3 },
    node: { keywords: ["node.js", "nodejs", "node js"], points: 3 },
    express: { keywords: ["express", "expressjs", "express.js"], points: 3 },
    fullstack: {
      keywords: ["full stack", "fullstack", "full-stack"],
      points: 3,
    },
  },

  mediumPriority: {
    postgresql: { keywords: ["postgresql", "postgres", "psql"], points: 2 },
    dashboard: {
      keywords: ["dashboard", "admin panel", "admin dashboard"],
      points: 2,
    },
    saas: { keywords: ["saas", "software as a service"], points: 2 },
    typescript: { keywords: ["typescript", "ts"], points: 2 },
    webapp: {
      keywords: ["web app", "web application", "web platform"],
      points: 2,
    },
    mvp: { keywords: ["mvp", "minimum viable product", "prototype"], points: 2 },
    internaltool: {
      keywords: ["internal tool", "internal dashboard", "back office"],
      points: 2,
    },
  },

  lowPriority: {
    tailwind: { keywords: ["tailwind", "tailwindcss"], points: 1 },
    api: {
      keywords: ["rest api", "api development", "api integration"],
      points: 1,
    },
    supabase: { keywords: ["supabase"], points: 1 },
    vercel: { keywords: ["vercel"], points: 1 },
    netlify: { keywords: ["netlify"], points: 1 },
    railway: { keywords: ["railway"], points: 1 },
    aws: { keywords: ["aws", "amazon web services", "s3", "ec2"], points: 1 },
    auth: { keywords: ["authentication", "auth", "oauth", "jwt"], points: 1 },
    stripe: { keywords: ["stripe", "payment integration", "payments"], points: 1 },
    crud: { keywords: ["crud", "data table", "data grid"], points: 1 },
  },
};

module.exports = keywords;
