const locations = {
  preferred: [
    "united states",
    "usa",
    "us",
    "united kingdom",
    "uk",
    "england",
    "scotland",
    "wales",
    "canada",
    "australia",
    "germany",
    "france",
    "italy",
    "spain",
    "netherlands",
    "belgium",
    "sweden",
    "norway",
    "denmark",
    "finland",
    "switzerland",
    "austria",
    "ireland",
    "portugal",
    "poland",
    "czech",
    "greece",
    "saudi arabia",
    "uae",
    "united arab emirates",
    "dubai",
    "qatar",
    "kuwait",
    "bahrain",
    "oman",
    "new york",
    "los angeles",
    "san francisco",
    "chicago",
    "boston",
    "seattle",
    "austin",
    "denver",
    "miami",
    "atlanta",
    "london",
    "manchester",
    "birmingham",
    "leeds",
    "bristol",
    "toronto",
    "vancouver",
    "montreal",
    "calgary",
    "sydney",
    "melbourne",
    "brisbane",
    "perth",
    "berlin",
    "munich",
    "frankfurt",
    "hamburg",
    "paris",
    "lyon",
    "marseille",
    "amsterdam",
    "rotterdam",
    "stockholm",
    "oslo",
    "copenhagen",
    "helsinki",
    "zurich",
    "geneva",
    "vienna",
    "dublin",
    "riyadh",
    "jeddah",
    "abu dhabi",
    "doha",
  ],

  redFlag: [
    "india",
    "pakistan",
    "vietnam",
    "bangladesh",
    "mumbai",
    "delhi",
    "new delhi",
    "noida",
    "gurgaon",
    "gurugram",
    "bangalore",
    "bengaluru",
    "hyderabad",
    "chennai",
    "pune",
    "kolkata",
    "ahmedabad",
    "jaipur",
    "karachi",
    "lahore",
    "islamabad",
    "rawalpindi",
    "ho chi minh",
    "hanoi",
    "dhaka",
    "philippines",
    "manila",
    "quezon city",
    "cebu",
    "davao",
  ],

  isPreferred(location) {
    if (!location) return false;
    const lower = location.toLowerCase();
    return this.preferred.some((loc) => lower.includes(loc));
  },

  isRedFlag(location) {
    if (!location) return false;
    const lower = location.toLowerCase();
    return this.redFlag.some((loc) => lower.includes(loc));
  },
};

module.exports = locations;
